Viewer integration
GEO-BON/bon-in-a-box-pipeline-engine pull request #107
Opened 2024-08-13 20:22 UTC by glaroc

2024-08-14 14:40 UTC, jmlord requested changes
Very rough review of code.
Still needs testing for dev and prod.

2024-08-14 14:40 UTC, jmlord commented on viewer/index.html
> +    <title>GEO BON - Bon-in-a-Box Results Viewer</title>
BON in a Box

2024-08-14 14:40 UTC, jmlord commented on viewer/public/logo192.png
à enlever

2024-08-14 14:40 UTC, jmlord commented on viewer/public/logo512.png
à enlever

2024-08-14 14:40 UTC, jmlord commented on viewer/public/manifest.json
Est-ce que ce fichier est également nécessaire avec vite?
Si oui, modifier

2024-08-14 14:40 UTC, jmlord commented on viewer/public/vite.svg
enlever

2024-08-14 14:40 UTC, jmlord commented on viewer/src/App.css
ces styles semblent tous déconnectés de l'app actuelle (proviennent de la démo?)

2024-08-14 14:40 UTC, jmlord commented on viewer/src/App.test.tsx
enlever... à moins qu'on veule faire des tests du UI!! Ce qui ne serait pas fou, franchement... mais je crois pas qu'on ait le temps là...

2024-08-14 14:40 UTC, jmlord commented on viewer/src/assets/react.svg
enlever

2024-08-14 14:40 UTC, jmlord commented on viewer/src/components/Digitizer/index.tsx
C'est quoi ça un Digitizer?

2024-08-14 14:40 UTC, jmlord commented on viewer/src/components/Sidebar/variables.tsx
Semble un restant de quelque chose d'autre?

2024-08-14 14:40 UTC, jmlord commented on viewer/src/logo.svg
enlever

2024-08-14 20:28 UTC, glaroc commented on viewer/src/components/Digitizer/index.tsx
La partie à droite pour résumer une couche selon des polygones.

2024-08-14 20:28 UTC, glaroc commented on viewer/src/components/Sidebar/variables.tsx
Non, c'est utilisé

2024-08-21 17:43 UTC, jmlord approved these changes
Approved as beta. There is still a lot of polishing to do. And we should definitely think about sharing components with the UI. That might be easier with the Vite migration.

2024-08-21 17:44 UTC, merged