Add ability to view multiband tifs
GEO-BON/bon-in-a-box-pipeline-engine pull request #132
Opened 2024-09-23 16:56 UTC by glaroc

2024-09-24 19:45 UTC, jmlord approved these changes

2024-09-24 19:45 UTC, jmlord commented on viewer/src/helpers/biab_api.tsx
> +  if (value.type.includes("tif") && !value.outputs.includes(",")) {
commentaire svp à propos de ce que la virgule signifie et ce qui est fait dans un cas où l'autre.

Aussi, on peut imbriquer le if:
```
if (tif)
  if( , )
    bla bla
  else
    bla bla
```

2024-09-24 19:56 UTC, jmlord requested changes
Viewing a regular tiff from the hello world example does not work anymore!

2024-09-25 14:07 UTC, glaroc commented
@jmlord viewing single tif should work now.

2024-09-25 17:57 UTC, jmlord approved these changes

2024-09-25 18:33 UTC, merged